SELECT setval('curriculums_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('curriculums_id_seq'),2)-1 FROM curriculums));
SELECT setval('jurisdictions_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('jurisdictions_id_seq'),2)-1 FROM jurisdictions));
SELECT setval('presbyteries_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('presbyteries_id_seq'),2)-1 FROM presbyteries));
SELECT setval('address_types_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('address_types_id_seq'),2)-1 FROM address_types));
SELECT setval('states_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('states_id_seq'),2)-1 FROM states));
SELECT setval('volunteer_status_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('volunteer_status_id_seq'),2)-1 FROM volunteer_status));
SELECT setval('denominations_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('denominations_id_seq'),2)-1 FROM denominations));
SELECT setval('client_communication_types_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('client_communication_types_id_seq'),2)-1 FROM client_communication_types));
SELECT setval('addresses_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('addresses_id_seq'),2)-1 FROM addresses));
SELECT setval('relationship_preferences_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('relationship_preferences_id_seq'),2)-1 FROM relationship_preferences));
SELECT setval('churches_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('churches_id_seq'),2)-1 FROM churches));
SELECT setval('security_levels_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('security_levels_id_seq'),2)-1 FROM security_levels));
SELECT setval('genders_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('genders_id_seq'),2)-1 FROM genders));
SELECT setval('facilities_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('facilities_id_seq'),2)-1 FROM facilities));
SELECT setval('courses_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('courses_id_seq'),2)-1 FROM courses));
SELECT setval('client_status_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('client_status_id_seq'),2)-1 FROM client_status));
SELECT setval('lessons_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('lessons_id_seq'),2)-1 FROM lessons));
SELECT setval('persons_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('persons_id_seq'),2)-1 FROM persons));
SELECT setval('programs_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('programs_id_seq'),2)-1 FROM programs));
SELECT setval('clients_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('clients_id_seq'),2)-1 FROM clients));
SELECT setval('users_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('users_id_seq'),2)-1 FROM users));
SELECT setval('pastors_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('pastors_id_seq'),2)-1 FROM pastors));
SELECT setval('volunteers_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('volunteers_id_seq'),2)-1 FROM volunteers));
SELECT setval('volunteer_program_assignments_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('volunteer_program_assignments_id_seq'),2)-1 FROM volunteer_program_assignments));
SELECT setval('client_volunteer_assignments_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('client_volunteer_assignments_id_seq'),2)-1 FROM client_volunteer_assignments));
SELECT setval('client_communications_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('client_communications_id_seq'),2)-1 FROM client_communications));
SELECT setval('student_lessons_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('student_lessons_id_seq'),2)-1 FROM student_lessons));
SELECT setval('mentor_groups_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('mentor_groups_id_seq'),2)-1 FROM mentor_groups));
SELECT setval('schedule_entries_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('schedule_entries_id_seq'),2)-1 FROM schedule_entries));
SELECT setval('volunteer_credentials_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('volunteer_credentials_id_seq'),2)-1 FROM volunteer_credentials));
SELECT setval('mentor_group_assignments_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('mentor_group_assignments_id_seq'),2)-1 FROM mentor_group_assignments));
SELECT setval('parole_status_id_seq',(SELECT GREATEST(MAX(id)+1,nextval('parole_status_id_seq'),2)-1 FROM parole_status));

ALTER TABLE schema_migrations ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE schema_migrations ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE curriculums ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE curriculums ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE jurisdictions ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE jurisdictions ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE presbyteries ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE presbyteries ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE address_types ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE address_types ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE states ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE states ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE volunteer_status ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE volunteer_status ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE denominations ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE denominations ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE client_communication_types ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE client_communication_types ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE addresses ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE addresses ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE relationship_preferences ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE relationship_preferences ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE churches ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE churches ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE security_levels ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE security_levels ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE genders ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE genders ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE facilities ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE facilities ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE courses ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE courses ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE client_status ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE client_status ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE lessons ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE lessons ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE persons ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE persons ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE programs ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE programs ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE clients ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE clients ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE users ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE pastors ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE pastors ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE volunteers ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE volunteers ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE volunteer_program_assignments ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE volunteer_program_assignments ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE client_volunteer_assignments ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE client_volunteer_assignments ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE client_communications ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE client_communications ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE student_lessons ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE student_lessons ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE mentor_groups ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE mentor_groups ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE schedule_entries ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE schedule_entries ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE mentor_group_assignments ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE mentor_group_assignments ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE volunteer_credentials ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE volunteer_credentials ALTER COLUMN updated_at SET DEFAULT NOW();
ALTER TABLE parole_status ALTER COLUMN inserted_at SET DEFAULT NOW(); ALTER TABLE parole_status ALTER COLUMN updated_at SET DEFAULT NOW();
